### ISSUE TITLE
Microsoft .NET Framework error

### ISSUE THREAD

**Issue by ClaireRupikaING** [Fr33dan/GPSaveConverter#100] opened 2024-11-19 18:30 UTC
I get this error as soon as i open the .exe, even if i press continue nothing happens

![imagen](https://github.com/user-attachments/assets/37f8e4c3-45a2-4472-8771-26ce48f0bff7)

**Comment by Fr33dan** [comment] 2024-12-04 22:41
Duplicate of #95

**Closed by Fr33dan** 2024-12-04 22:41 UTC
