### ISSUE TITLE
Lego Star Wars Skywalker Saga error

### ISSUE THREAD

**Issue by tymcfie18** [Fr33dan/GPSaveConverter#39] opened 2023-01-29 23:49 UTC
I am trying to convert star wars skywalker saga from steam to Xbox, however, I keep getting this error. I have made the files lowercase as suggested in the other issue regarding this game, I have also downloaded the latest version of GPSaveConverter. 
![image](https://user-images.githubusercontent.com/123518919/215362986-743f2cb5-ae04-445e-b2e9-43d54cbffa42.png)

**Comment by Fr33dan** [comment] 2023-02-05 14:48
Duplicate of #27

**Closed by Fr33dan** 2023-02-05 14:48 UTC
